### PR TITLE
Fix: Mockserver (module is not defined)

### LINKED ISSUE #1: Karma opa5 plugin
Hi @matz3 @TobiasOetzel,

would it be possible to develop an karma opa5 plugin (maybe based on the [qunit plugin](https://github.com/karma-runner/karma-qunit))? 
I want to run the opa5 tests in an automated fashion and get back structured results via tha karma junit reporter or the CLI. With a karma opa5 plugin we could easily benefit from the existing reporters etc.

Best Regards Christian

### PR DESCRIPTION
**Pull request by janmattfeld**
Fixes #1:
Uncaught ReferenceError: module is not defined
at /node_modules/karma-openui5/lib/mockserver.js:7

I hereby declare to agree to the OpenUI5 Individual Contributor License
Agreement.

### CODE REVIEW

File: src/mockserver.js [hunk 1]
```diff
@@ -1,9 +1,12 @@
 var config = window.__karma__.config,
-	ui5config = (config && config.openui5) || {},
+	ui5config = (config && config.openui5.config) || {},
 	mockserverConfig = ui5config.mockserver || {};
 
 //workaround for crossroads/mockserver issue
 (function() {
+	if (typeof module === undefined) {
+		var module = '';
```
Comment (cevou) [inline src/mockserver.js]: This is wrong. If `module` is `undefined` it should stay `undefined`and should not be made to an emtpy string.

File: src/mockserver.js [hunk 2]
```diff
@@ -1,9 +1,12 @@
 var config = window.__karma__.config,
-	ui5config = (config && config.openui5) || {},
+	ui5config = (config && config.openui5.config) || {},
```
Comment (cevou) [inline src/mockserver.js]: If you cange this, the next line will not work anymore. `ui5config.mockserver` will never be defined.

Comment (janmattfeld) [inline src/mockserver.js]: So the correct point to insert the mockserver in marma.conf.js is on the same level as config? That is working, thanks.
```javascript
module.exports = function(config) {
	config.set({
		basePath: '',
		frameworks: ['qunit','openui5'],
		files: [
			{ pattern: 'bower_components/openui5-sap.ui.core/resources/**/*', served: true, included: false, watched: false },
			{ pattern: 'bower_components/openui5-sap.m/resources/**/*', served: true, included: false, watched: false },
			{ pattern: 'bower_components/openui5-themelib_sap_bluecrystal/resources/**/*', served: true, included: false, watched: false },
			{ pattern: 'src/**/*', served: true, included: false, watched: true },
			{ pattern: 'test/**/*.qunit.js', served: true, included: true, watched: true }
		],
		preprocessors: {
			'src/**/*.js': ['coverage']
		},
		openui5: {
			path: 'bower_components/openui5-sap.ui.core/resources/sap-ui-core.js',
			useMockServer: true
		},
		client: {
			openui5: {
				config: {
					theme: 'sap_bluecrystal',
					libs: 'sap.m',
					resourceroots: {
						'sap.m': '/base/bower_components/openui5-sap.m/resources/sap/m',
						'my.namespace': '/base/src/my/namespace'
					},
					themeroots: {
						'sap_bluecrystal': '/base/bower_components/openui5-themelib_sap_bluecrystal/resources'
					}
				},
				mockserver: {
					config: {
						autoRespond: true
					},
					rootUri: 'http://myserver.de:8000/sap/opu/odata/sap/Z_PACKAGE_SRV/',
					metadataURL: '/base/test/service/metadata.xml',
					mockdataSettings: '/base/test/service'
				}
			}
		},
		reporters: ['progress', 'coverage'],
		coverageReporter: {
			type : 'html',
			dir : 'coverage'
		},
		port: 9876,
		colors: true,
		logLevel: config.LOG_INFO,
		autoWatch: true,
		browsers: ['Chrome'],
		singleRun: false
	});
};
```

File: src/mockserver.js (hunk 1 above)
Comment (janmattfeld) [inline src/mockserver.js]: Aggreed. So it should be:
```javascript
if (typeof module === undefined){
  var module = undefined;
}
```
If i don't add these lines I am still getting an Uncaught ReferenceError at line 9 because module is not defined.

Comment (cevou) [inline src/mockserver.js]: `var original = module;`is normally handled like `var original = undefined;` if module was not defined before. What kind of environment are you using to execute the tests?

**Comment by matz3** [comment]
@cevou did you want to have a look into this?
I can do so after my 2 week vacation if this is still relevant?

**Comment by cevou** [comment]
There was an error in janmattfeld's config. There was no issue.

**Comment by agrz** [comment]
I think here are mixed up two issues. The wrong config and the module is not defined error.
The later I can reproduce on Windows with Karma 0.13.5, karma-openui5 0.2.1 and karma-chrome-launcher 0.2.2 when using a mockserver.
Adding the code snippet proposed by janmattfeld solves the problem:
```javascript
if (typeof module === undefined){
  var module = undefined;
}
```
Maybe this is something that needs to be fixed or am I missing something else?

**Comment by matz3** [comment]
@agrz thanks for the details. Could you please also share your `karma.conf.js` to make sure I use the same setup to reproduce this issue?

**Comment by agrz** [comment]
I created a small sample project based on the OpenUi5 tutorial.
You can find it in my Github space:

**Comment by matz3** [comment]
Thank you @agrz. I could find out what causes this issue.

It happens when using the mockserver feature and QUnit is NOT loaded.
Accessing a undefined variable (`module`) without a scope (like `this` or `window`) throws an error.

You can "workaround" this issue by specifying the `frameworks` in your `karma.conf.js` in the right order (`openui5` before `qunit`). See more details about this here: https://github.com/SAP/openui5/issues/557#issuecomment-135375458.

Nevertheless this PR is absolutely valid and this should be fixed.
@janmattfeld: I've added a comment to your code with my proposal to fix this. If you have the time it would be great if you could update it. Otherwise everyone is welcome to contribute a PR.

File: src/mockserver.js (hunk 1 above)
Comment (matz3) [inline src/mockserver.js]: See my comment https://github.com/SAP/karma-openui5/pull/2#issuecomment-170025760
I would suggest to fix it like this
```js
var original;
if (typeof module !== "undefined") {
	original = module;
	module = undefined;
}
jQuery.sap.require("sap.ui.core.util.MockServer");
if (typeof original !== "undefined") {
	module = original;
	original = undefined;
}
```

**Comment by agrz** [comment]
Changing the order works, thank you.
Perhaps it would help to provide some basic tutorial how to use karma-openui5 and point such things out.

**Comment by matz3** [comment]
Makes sense. Would a How-To / Troubleshooting section in the README be fine for you?

File: src/mockserver.js (hunk 2 above)
Comment (matz3) [inline src/mockserver.js]: Could you please revert this change? It should not be necessary.

**Comment by matz3** [comment]
Thanks @janmattfeld :+1: 
Could you please have a look into my comment and squash all the commits into one? (via interactive rebase)

**Comment by matz3** [comment]
Thanks :tada:
